name: Chainguard Registry Example

on:
  push:
    branches: ['main']

permissions:
  contents: read
  id-token: write  # This is needed for OIDC federation.

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $PATH
          env
      - uses: actions/checkout@v3
      - uses: found-it/chainguard-actions/setup-chainctl@setup-chainctl-remove-sudo
        with:
          identity: 99875baff2b3c7cb15ecb743bc00d2da9d65f78c/96007ab0b6b04a73
      - run: docker pull cgr.dev/chainguard/node
