name: Chainguard Registry Example

on:
  push:
    branches: ['main']

permissions:
  contents: read
  id-token: write  # This is needed for OIDC federation.

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chainguard-dev/actions/setup-chainctl@main
        with:
          identity: 99875baff2b3c7cb15ecb743bc00d2da9d65f78c/d4d92eba1e15bc0d
      - run: docker pull cgr.dev/chainguard/node
